language: php

php:
  - 7.4
  # @see https://travis-ci.community/t/php-8-0-missing/10132
  # - 8.1
  - nightly

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
      env: SYMFONY_VERSION=4.*
    - php: 7.4
      env: SYMFONY_VERSION=5.*
    - php: 7.4
      env: SYMFONY_VERSION="dev-master"
    - php: 7.4
      env: ISOCODES_VERSION=2.1.*
    - php: 7.4
      env: ISOCODES_VERSION="dev-master"
  allow_failures:
    - php: nightly
    - env: SYMFONY_VERSION="dev-master"
    - env: ISOCODES_VERSION="dev-master"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files


install:
  - composer global require satooshi/php-coveralls:@stable codeclimate/php-test-reporter:@stable --no-update
  - composer global update --prefer-dist --no-interaction
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; PHPUNIT_OPTION="--testsuite symfony"; fi;
  - if [ "$ISOCODES_VERSION" != "" ]; then composer require "ronanguilloux/isocodes:${ISOCODES_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: XDEBUG_MODE=coverage ./vendor/bin/simple-phpunit --coverage-clover build/logs/clover.xml ${PHPUNIT_OPTION}

after_script:
  - coveralls -v
  - test-reporter
